version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ..:/workspace/app
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nestjs_dev

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres-data:
